###############################################
# リクエストテスト定義情報 => rest-client.env.json
###############################################
###### MateriaWeb.AuthenticatorController
### :sign_in
POST   {{url}}/api/sign-in   HTTP/1.1
Content-Type: application/json

{
  "email": "{{login_email}}",
  "password": "{{login_password}}"
}

> {%
    client.global.set("access_token",  response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
    client.global.set("user_id",       response.body.id);
  %}

###############################################
###### MateriaCommerceWeb.ItemController
### :index
GET    {{url}}/api/items     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

> {%
    client.global.set("item_id",  response.body[0].id);
  %}

### :show
GET    {{url}}/api/items/{{item_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### :create
POST   {{url}}/api/items     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "ItemNameTest",
  "item_code": "ItemCode",
  "start_datetime": "1999-12-31 23:59:59Z",
  "end_datetime": "2999-12-31 23:59:59Z",
  "inserted_id": 1
}

> {%
    client.global.set("item_id",  response.body.id);
  %}

### :update
PUT    {{url}}/api/items/{{item_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "ItemNameTest_Update",
  "item_code": "ItemCode_Update",
  "start_datetime": "2000-12-31 23:59:59Z",
  "end_datetime": "2999-12-31 23:59:59Z"
}

### :delete
DELETE {{url}}/api/items/{{item_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### :search_current_items
POST   {{url}}/api/search-items HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "and": [{"item_code": "ICZ1000"}],
  "or": []
}

### :search_current_items
POST   {{url}}/api/search-items HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "and": [],
  "or": [{"model_number": "Z1000"}]
}

### :search_current_items
POST   {{url}}/api/search-items HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{}

### :current_contracts
POST   {{url}}/api/current-items     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "item_code": "ICZ1000",
    "category1": "電化製品",
    "name": "炊飯器Z1000!!",
    "lock_version": 0
}

###############################################
###### MateriaCommerceWeb.TaxController
### :index
GET    {{url}}/api/taxes     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

> {%
    client.global.set("tax_id",  response.body[0].id);
  %}

### :show
GET    {{url}}/api/taxes/{{tax_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### :create
POST   {{url}}/api/taxes     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "TaxNameTest",
  "tax_category": "TaxCategory1",
  "tax_rate": 0.5,
  "start_datetime": "1999-12-31 23:59:59Z",
  "end_datetime": "2999-12-31 23:59:59Z",
  "inserted_id": 1
}

> {%
    client.global.set("tax_id",  response.body.id);
  %}

### :update
PUT    {{url}}/api/taxes/{{tax_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "TaxNameTest_Update",
  "tax_category": "TaxCategory1_Update",
  "tax_rate": 100,
  "start_datetime": "2000-12-31 23:59:59Z",
  "end_datetime": "2999-12-31 23:59:59Z"
}

### :delete
DELETE {{url}}/api/taxes/{{tax_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### :search_current_taxes
POST   {{url}}/api/search-taxes     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "and": [{"tax_category": "category2"}],
  "or": []
}

### :search_current_taxes
POST   {{url}}/api/search-taxes     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "and": [],
  "or": [{"tax_rate": "1"}]
}

### :search_current_taxes
POST   {{url}}/api/search-taxes     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{}

### :current_taxes
POST   {{url}}/api/current-taxes     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "tax_category": "category1",
    "tax_rate": 200,
    "lock_version": 0
}

###############################################
###### MateriaCommerceWeb.PriceController
### :index
GET    {{url}}/api/prices     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

> {%
    client.global.set("price_id",  response.body[0].id);
  %}

### :show
GET    {{url}}/api/prices/{{price_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### :create
POST   {{url}}/api/prices     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "item_code": "ItemCode",
  "unit_price": 10.5,
  "start_datetime": "1999-12-31 23:59:59Z",
  "end_datetime": "2999-12-31 23:59:59Z",
  "inserted_id": 1
}

> {%
    client.global.set("price_id",  response.body.id);
  %}

### :update
PUT    {{url}}/api/prices/{{price_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "item_code": "ItemCode_Update",
  "unit_price": 1000.5,
  "start_datetime": "1999-12-31 23:59:59Z",
  "end_datetime": "2999-12-31 23:59:59Z"
}

### :delete
DELETE {{url}}/api/prices/{{price_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### :search_current_prices
POST   {{url}}/api/search-prices HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "and": [{"item_code": "ICZ1001"}],
  "or": []
}

### :search_current_prices
POST   {{url}}/api/search-prices HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "and": [],
  "or": [{"unit_price": "1000"}]
}

### :search_current_prices
POST   {{url}}/api/search-prices HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{}

### :current_prices
POST   {{url}}/api/current-prices     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "item_code": "ICZ1000",
    "unit_price": 0,
    "description": "description",
    "lock_version": 0
}

###############################################
###### MateriaCommerceWeb.ContractController
### :index
GET    {{url}}/api/contracts     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

> {%
    client.global.set("contract_id",  response.body[0].id);
  %}

### :show
GET    {{url}}/api/contracts/{{contract_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### :create
POST   {{url}}/api/contracts     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "contract_no": "Contract-Number",
  "start_datetime": "1999-12-31 23:59:59Z",
  "end_datetime": "2999-12-31 23:59:59Z",
  "inserted_id": 1
}

> {%
    client.global.set("contract_id",  response.body.id);
  %}

### :update
PUT    {{url}}/api/contracts/{{contract_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "contract_no": "Contract-Number_Update",
  "start_datetime": "1999-12-31 23:59:59Z",
  "end_datetime": "2999-12-31 23:59:59Z"
}

### :delete
DELETE {{url}}/api/contracts/{{contract_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### :search_current_contracts
POST   {{url}}/api/search-contracts     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "and": [{"contract_no": "1111-1111-1111"}],
  "or": []
}

### :search_current_contracts
POST   {{url}}/api/search-contracts     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "and": [],
  "or": [{"settlement": "9999-9999-9999"}]
}

### :search_current_contracts
POST   {{url}}/api/search-contracts     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{}

### :current_contracts
POST   {{url}}/api/current-contracts     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "contract_no": "1111-1111-1111",
    "settlement": "8888-8888-8888",
    "lock_version": 0
}

###############################################
###### MateriaCommerceWeb.ContractDetailController
### :index
GET    {{url}}/api/contract_details     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

> {%
    client.global.set("contract_detail_id",  response.body[0].id);
  %}

### :show
GET    {{url}}/api/contract_details/{{contract_detail_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### :create
POST   {{url}}/api/contract_details     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "contract_no": "Contract-Number",
  "start_datetime": "1999-12-31 23:59:59Z",
  "end_datetime": "2999-12-31 23:59:59Z",
  "inserted_id": 1
}

> {%
    client.global.set("contract_detail_id",  response.body.id);
  %}

### :update
PUT    {{url}}/api/contract_details/{{contract_detail_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "contract_no": "Contract-Number_Update",
  "start_datetime": "1999-12-31 23:59:59Z",
  "end_datetime": "2999-12-31 23:59:59Z"
}

### :delete
DELETE {{url}}/api/contract_details/{{contract_detail_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### :search_current_contract_details
POST   {{url}}/api/search-contract-details     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "and": [{"contract_no": "1111-1111-1111"}],
  "or": []
}

### :search_current_contract_details
POST   {{url}}/api/search-contract-details     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "and": [],
  "or": [{"price": "100"}]
}

### :search_current_contract_details
POST   {{url}}/api/search-contract-details     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{}

### :current_contract_details
POST   {{url}}/api/current-contract-details     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "contract_no": "1111-1111-1111",
  "contract_details":
  [
    {
      "contract_no": "1111-1111-1111",
      "contract_name": "Update",
      "amount": 2,
      "price": 200,
      "id": 6,
      "lock_version": 0
    },
    {
      "contract_no": "1111-1111-1111",
      "contract_name": "NewRecord",
      "amount": 3,
      "price": 300
    }
  ]
}

###############################################
###### MateriaCommerceWeb.RequestController
### :index
GET    {{url}}/api/requests     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

> {%
    client.global.set("request_id",  response.body[0].id);
  %}

### :show
GET    {{url}}/api/requests/{{request_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### :create
POST   {{url}}/api/requests     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "request_number": "request-Number",
  "start_datetime": "1999-12-31 23:59:59Z",
  "end_datetime": "2999-12-31 23:59:59Z",
  "inserted_id": "1"
}

> {%
    client.global.set("request_id",  response.body.id);
  %}

### :update
PUT    {{url}}/api/requests/{{request_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "request_number": "request-Number_Update",
  "start_datetime": "1999-12-31 23:59:59Z",
  "end_datetime": "2999-12-31 23:59:59Z",
  "inserted_id": "1"
}

### :delete
DELETE {{url}}/api/requests/{{request_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### :search_current_requests
POST   {{url}}/api/search-requests     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "and": [{"request_number": "PJ-01"}],
  "or": []
}

### :search_current_requests
POST   {{url}}/api/search-requests     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "and": [],
  "or": [{"request_key1": "key1"}]
}

### :search_current_requests
POST   {{url}}/api/search-requests     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{}

### :current_requests
POST   {{url}}/api/current-requests     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
    "request_number": "PJ-01",
    "status": "99",
    "user_id": "1",
    "lock_version": 2
}

###############################################
###### MateriaCommerceWeb.RequestAppendixController
### :index
GET    {{url}}/api/request_appendices     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

> {%
    client.global.set("request_appendix_id",  response.body[0].id);
  %}

### :show
GET    {{url}}/api/request_appendices/{{request_appendix_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### :create
POST   {{url}}/api/request_appendices     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "request_number": "request-Number",
  "start_datetime": "1999-12-31 23:59:59Z",
  "end_datetime": "2999-12-31 23:59:59Z",
  "inserted_id": "1",
  "appendix_category": "Appendix_Category1"
}

> {%
    client.global.set("request_appendix_id",  response.body.id);
  %}

### :update
PUT    {{url}}/api/request_appendices/{{request_appendix_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "request_number": "request-Number_Update",
  "start_datetime": "1999-12-31 23:59:59Z",
  "end_datetime": "2999-12-31 23:59:59Z",
  "inserted_id": "1",
  "appendix_category": "Appendix_Category1_Update"
}

### :delete
DELETE {{url}}/api/request_appendices/{{request_appendix_id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

### :search_current_request_appendices
POST   {{url}}/api/search-request-appendices     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "and": [{"request_number": "PJ-01"}],
  "or": []
}

### :search_current_request_appendices
POST   {{url}}/api/search-request-appendices     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "and": [{"request_number": "PJ-01"}],
  "or": [{"appendix_category": "Category1"}, {"appendix_category": "Category4"}]
}

### :search_current_request_appendices
POST   {{url}}/api/search-request-appendices     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{}

### :current_contracts
POST   {{url}}/api/current-request-appendices     HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "request_number": "PJ-01",
  "request_appendices":
  [
    {
      "request_number": "PJ-01",
      "appendix_category": "Category4",
      "id": 5,
      "lock_version": 0
    },
    {
      "request_number": "PJ-01",
      "appendix_category": "Category5"
    }
  ]
}
###
